# vim: nospell
#
language: minimal
dist: trusty
sudo: false

cache:
  timeout: 600
  directories:
    - $HOME/.stack/snapshots
    - .stack-work/install

before_cache:
  - rm -vrf $(stack path --local-install-root)/bin
  - rm -rf  $(stack path --local-install-root)/doc

addons:
  apt:
    sources: &apt_sources
      - hvr-ghc

    packages: &apt_packages
      - alex-3.1.7
      - cabal-install-1.24
      - cabal-install-2.0
      - cabal-install-2.2
      - happy-1.19.5
      - libgmp-dev

matrix:
  fast_finish: true
  include:
    - env: GHC=8.6.1 CABAL=2.2
      compiler: "GHC 8.6"

    - env: GHC=8.4.3 CABAL=2.0
      compiler: "GHC 8.4"

    - env: GHC=8.2.2 CABAL=2.0
      compiler: "GHC 8.2"

    - env: GHC=8.0.2 CABAL=1.24
      compiler: "GHC 8.0"

    # - env: GHC=head CABAL=head
    #   compiler: "GHC HEAD"
    #   addons: { apt: { sources: [ hvr-ghc ], packages: [ ghc-head, cabal-install-head, happy-1.19.5, alex-3.1.7 ] }}

  # allow_failures:
  #   - env: GHC=head CABAL=head

before_install:
  - export PATH=/opt/cabal/${CABAL}/bin:/opt/alex/3.1.7/bin:/opt/happy/1.19.5/bin:${HOME}/.cabal/bin:${PATH}
  - source .travis/install-stack.sh
  - |
      case ${GHC%.*} in
        8.0) ;; # too slow ._.
        *  ) export HADDOCK="--haddock --no-haddock-deps" ;;
      esac

install:
  - echo "$(stack exec ghc -- --version) [$(stack exec ghc -- --print-project-git-commit-id 2> /dev/null || echo '?')]"
  - cabal --version
  - stack --version
  - travis_retry stack build --fast --jobs=2 --test --only-dependencies --no-terminal --no-copy-bins

script:
  - stack build --fast --jobs=2 --test --no-terminal --no-copy-bins --no-run-tests ${HADDOCK}
  - stack test accelerate:doctest
  - stack test accelerate:nofib-interpreter --test-arguments='--hedgehog-tests 25'

after_success:
  - source .travis/update-accelerate-buildbot.sh

